<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('73', '/uploads/allimg/170907/1-1FZG649444K.JPG');
$maNum = 1;
$myaddons[$maNum] = array('74', '/uploads/allimg/170907/1-1FZGA01BT.jpg');
$maNum = 2;
$myaddons[$maNum] = array('75', '/uploads/allimg/170907/1-1FZGA034313.jpg');
$maNum = 3;
$myaddons[$maNum] = array('76', '/uploads/allimg/170907/1-1FZGA05B02.jpg');
$maNum = 4;
$myaddons[$maNum] = array('77', '/uploads/allimg/170907/1-1FZGA113A7.jpg');
$maNum = 5;
