<tr>
									<td width="82%" height="40" align="left" valign="middle" class="heis" style=" border-bottom:#cccccc dashed 1px"><a href="news.asp?Classid=7"><span style="color:#055a97; font-weight:bold">[公司新闻]</span></a>&nbsp;&nbsp;<a href="?ID=6&amp;ClassID=7" class="heis" target="_blank">&nbsp; &gt;&gt; 昆山装修水电工注意事项</a></td>
									<td width="18%" align="right" valign="middle" class="heis" style=" border-bottom:#cccccc dashed 1px">[2018-4-23]&nbsp; </td>
								</tr>