<div class="carousel-feature"><a title="[field:title/]" href="[field:arcurl/]" target="_blank"><img src="[field:picname/]" alt="[field:title/]" height="315" class="carousel-image PicAuto" width="420" /></a>
              <div class="carousel-caption"><a title="[field:title/]" href="[field:arcurl/]" target="_blank"> [field:title/]</a>
                <p>[field:description function="cn_substr(@me,150)"/]... <span><a title="[field:title/]" href="[field:arcurl/]" target="_blank">[更多] </a></span></p>
                <a class="casemore" href="[field:arcurl/]">更多</a> </div>
            </div>