<?php
$z[0]=Array("title","",40,54);
$z[1]=Array("arcurl","",62,77);
$z[2]=Array("picname","",105,121);
$z[3]=Array("title","",128,142);
$z[4]=Array("title","",262,276);
$z[5]=Array("arcurl","",284,299);
$z[6]=Array("title","",318,332);
$z[7]=Array("description","",357,407);
$z[7][4]['function']="cn_substr(@me,150)";
$z[8]=Array("title","",427,441);
$z[9]=Array("arcurl","",449,464);
$z[10]=Array("arcurl","",550,565);

?>