<?php
$z[0]=Array("arcurl","",13,28);
$z[1]=Array("title","",53,67);
$z[2]=Array("picname","",114,130);
$z[3]=Array("arcurl","",207,222);
$z[4]=Array("title","",247,261);
$z[5]=Array("title","",316,330);
$z[6]=Array("arcurl","",359,374);
$z[7]=Array("pubdate","",502,549);
$z[7][4]['function']="GetDateTimeMK(@me)";
$z[8]=Array("description","",598,648);
$z[8][4]['function']="cn_substr(@me,150)";

?>