<tr>
									<td width="82%" height="40" align="left" valign="middle" class="heis" style=" border-bottom:#cccccc dashed 1px"><a href="[field:arcurl/]"><span style="color:#055a97; font-weight:bold">[公司新闻]</span></a>&nbsp;&nbsp;<a href="[field:arcurl/]" class="heis" target="_blank">&nbsp; &gt;&gt; [field:title/]</a></td>
									<td width="18%" align="right" valign="middle" class="heis" style=" border-bottom:#cccccc dashed 1px">[2018-4-23]&nbsp; </td>
								</tr>