<?php
$z[0]=Array("top","\r\n  <m:item name='插件管理器' link='plus_main.php' rank='10' target='main' />\r\n  <m:item name='挑错管理' link='erraddsave.php' rank='plus_挑错管理' target='main' />\r\n<m:item name='百度新闻' link='baidunews.php' rank='plus_百度新闻' target='main' />\r\n<m:item name='文件管理器' link='file_manage_main.php' rank='plus_文件管理器' target='main' />\r\n<m:item name='广告管理' link='ad_main.php' rank='plus_广告管理' target='main' />\r\n<m:item name='友情链接' link='friendlink_main.php' rank='plus_友情链接模块' target='main' />\r\n<m:item name='投票模块' link='vote_main.php' rank='plus_投票模块' target='main' />\r\n\r\n",53,777);
$z[0][4]['item']="7";
$z[0][4]['name']="辅助插件";
$z[0][4]['display']="block";
$z[1]=Array("top","\r\n<m:item name='德得模块' link='mda_main.php' rank='plus_广告管理' target='main'/>\r\n<m:item name='广告管理' link='mda_main.php?dopost=place' rank='plus_广告管理' target='main'/>\r\n<m:item name='查看报表' link='mda_main.php?dopost=report' rank='plus_广告管理' target='main'/>\r\n<m:item name='结算中心' link='mda_main.php?dopost=account' rank='plus_广告管理' target='main'/>\r\n<m:item name='德得设置' link='mda_main.php?dopost=setting' rank='plus_广告管理' target='main'/>\r\n",781,1341);
$z[1][4]['name']="德得广告";
$z[1][4]['display']="block";

?>