
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:phoneNum itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phoneNum>

<field:email itemname="邮箱地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:message itemname="消息内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:message>
