<?php
$z[0]=Array("field","",250,269);
$z[0][4]['name']="title";
$z[1]=Array("global","",270,296);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",336,365);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",404,462);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",809,844);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1001,1030);
$z[5][4]['name']="position";
$z[6]=Array("field","",1128,1186);
$z[6][4]['name']="typeid";
$z[6][4]['function']="GetTopTypename(@me)";
$z[7]=Array("channel","\n        <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\n        ",1212,1443);
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="<li><a href='~typelink~' class='con'>~typename~</a></li>";
$z[8]=Array("global","",1558,1579);
$z[8][4]['name']="cfg_dz";
$z[9]=Array("global","",1603,1625);
$z[9][4]['name']="cfg_tel";
$z[10]=Array("global","",1649,1670);
$z[10][4]['name']="cfg_cz";
$z[11]=Array("global","",1692,1713);
$z[11][4]['name']="cfg_qq";
$z[12]=Array("field","",1960,1981);
$z[12][4]['name']="content";
$z[13]=Array("include","",2201,2238);
$z[13][4]['filename']="footer.htm";

?>