<li class="newprod_list">
                 			<div class="newprod_pic"><a href="[field:arcurl/]"  class="pro_img_link"><img dataid="289098" width="220" src="[field:picname/]" alt="[field:title/]" class="289098" height="165" /></a>
                 		  </div>
                 			<div class="newprod_name"><a href="[field:arcurl/]"  title="[field:title/]}">[field:title/]</a></div>
                 		</li>