<?php
$z[0]=Array("field","",250,269);
$z[0][4]['name']="title";
$z[1]=Array("global","",270,296);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",336,358);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",397,448);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",867,902);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1062,1091);
$z[5][4]['name']="position";
$z[6]=Array("field","",1189,1247);
$z[6][4]['name']="typeid";
$z[6][4]['function']="GetTopTypename(@me)";
$z[7]=Array("channel","\n        <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\n        ",1273,1504);
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="<li><a href='~typelink~' class='con'>~typename~</a></li>";
$z[8]=Array("global","",1619,1640);
$z[8][4]['name']="cfg_dz";
$z[9]=Array("global","",1664,1686);
$z[9][4]['name']="cfg_tel";
$z[10]=Array("global","",1710,1731);
$z[10][4]['name']="cfg_cz";
$z[11]=Array("field","",2026,2045);
$z[11][4]['name']="title";
$z[12]=Array("field","",2082,2100);
$z[12][4]['name']="body";
$z[13]=Array("prenext","",2140,2165);
$z[13][4]['get']="pre";
$z[14]=Array("prenext","",2182,2208);
$z[14][4]['get']="next";
$z[15]=Array("include","",2431,2468);
$z[15][4]['filename']="footer.htm";

?>