<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,363);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",403,454);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",886,921);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1087,1116);
$z[5][4]['name']="position";
$z[6]=Array("field","",1218,1276);
$z[6][4]['name']="typeid";
$z[6][4]['function']="GetTopTypename(@me)";
$z[7]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n        ",1304,1539);
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="<li><a href='~typelink~' class='con'>~typename~</a></li>";
$z[8]=Array("global","",1658,1679);
$z[8][4]['name']="cfg_dz";
$z[9]=Array("global","",1704,1726);
$z[9][4]['name']="cfg_tel";
$z[10]=Array("global","",1751,1772);
$z[10][4]['name']="cfg_cz";
$z[11]=Array("field","",2076,2095);
$z[11][4]['name']="title";
$z[12]=Array("field","",2133,2151);
$z[12][4]['name']="body";
$z[13]=Array("prenext","",2192,2217);
$z[13][4]['get']="pre";
$z[14]=Array("prenext","",2235,2261);
$z[14][4]['get']="next";
$z[15]=Array("include","",2493,2530);
$z[15][4]['filename']="footer.htm";

?>