<?php
$z[0]=Array("field","",33,59);
$z[0][4]['name']="hover";
$z[1]=Array("field","",70,98);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",125,154);
$z[2][4]['name']="typename";
$z[3]=Array("field","",182,211);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n            <li class='li-level-1 item-li'>\r\n              <div class=\"cat-item\">\r\n                <div class='cat-name cat-name-1 cat-name-z' id='cat-id-26678'><a href=\"[field:typelink/]\"> [field:typename/]</a></div>\r\n              </div>\r\n            </li>\r\n            ",299,620);
$z[4][4]['type']="son";

?>