<li id="about" class="nav-lilink {dede:field name='hover'/}"><a href="{dede:field name='typeurl'/}" class="nav-alink" title="{dede:field name='typename'/}"
                       > {dede:field name='typename'/}</a>
        <div class="exnav">
          <ul class="children level-0">
            {dede:channel   type ='son'    }
            <li class='li-level-1 item-li'>
              <div class="cat-item">
                <div class='cat-name cat-name-1 cat-name-z' id='cat-id-26678'><a href="[field:typelink/]"> [field:typename/]</a></div>
              </div>
            </li>
            {/dede:channel}
          </ul>
        </div>
      </li>