<dl>
          <dt><a title="[field:title/]" href="[field:arcurl/]" target="_blank"><img dataid="26665" width="193" src="[field:picname/]" alt="[field:title/]" class="26665" height="143" /></a></dt>
          <dd>
            <h3><a title="[field:title/]" href="[field:arcurl/]" target="_blank"> [field:title/]</a></h3>
            <p>[field:description function="cn_substr(@me,150)"/]... <span><a title="[field:title/]" href="[field:arcurl/]" target="_blank">[更多]</a></span></p>
          </dd>
        </dl>