<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\"><span>友情链接：</span></a>",203,297);
$z[0][4]['typeid']="1";
$z[1]=Array("flink"," [field:link /] ",298,363);
$z[1][4]['row']="10";
$z[1][4]['type']="textall";
$z[2]=Array("flink"," [field:link /] ",577,642);
$z[2][4]['row']="10";
$z[2][4]['type']="textall";
$z[3]=Array("global","",865,892);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("global","",919,947);
$z[4][4]['name']="cfg_indexname";
$z[5]=Array("global","",950,978);
$z[5][4]['name']="cfg_indexname";
$z[6]=Array("channel","|\r\n                    <a href=\"[field:typelink/]\" class=\"nav-alink\" title=\"[field:typename/]\"> [field:typename/]</a> ",982,1142);
$z[6][4]['type']="top";
$z[7]=Array("global","",1264,1290);
$z[7][4]['name']="cfg_webname";
$z[8]=Array("global","",1311,1335);
$z[8][4]['name']="cfg_beian";
$z[9]=Array("global","",1341,1362);
$z[9][4]['name']="cfg_dz";
$z[10]=Array("global","",1377,1399);
$z[10][4]['name']="cfg_tel";
$z[11]=Array("global","",1414,1435);
$z[11][4]['name']="cfg_cz";
$z[12]=Array("global","",1777,1803);
$z[12][4]['name']="cfg_powerby";

?>