<?php
$z[0]=Array("channel","\r\n                    <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                    ",229,516);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[0][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[1]=Array("global","",604,630);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",637,658);
$z[2][4]['name']="cfg_dz";
$z[3]=Array("global","",673,695);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",710,731);
$z[4][4]['name']="cfg_cz";
$z[5]=Array("global","",947,973);
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",974,998);
$z[6][4]['name']="cfg_beian";

?>