<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\"><span>友情链接：</span></a>",198,292);
$z[0][4]['typeid']="1";
$z[1]=Array("flink"," [field:link /] ",293,358);
$z[1][4]['row']="10";
$z[1][4]['type']="textall";
$z[2]=Array("flink"," [field:link /] ",563,628);
$z[2][4]['row']="10";
$z[2][4]['type']="textall";
$z[3]=Array("global","",842,869);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("global","",896,924);
$z[4][4]['name']="cfg_indexname";
$z[5]=Array("global","",927,955);
$z[5][4]['name']="cfg_indexname";
$z[6]=Array("channel","|\n                    <a href=\"[field:typelink/]\" class=\"nav-alink\" title=\"[field:typename/]\"> [field:typename/]</a> ",959,1118);
$z[6][4]['type']="top";
$z[7]=Array("global","",1235,1261);
$z[7][4]['name']="cfg_webname";
$z[8]=Array("global","",1282,1306);
$z[8][4]['name']="cfg_beian";
$z[9]=Array("global","",1312,1333);
$z[9][4]['name']="cfg_dz";
$z[10]=Array("global","",1348,1370);
$z[10][4]['name']="cfg_tel";
$z[11]=Array("global","",1385,1406);
$z[11][4]['name']="cfg_cz";
$z[12]=Array("global","",1746,1772);
$z[12][4]['name']="cfg_powerby";

?>