<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\"><span>友情链接：</span></a>",195,289);
$z[0][4]['typeid']="9";
$z[1]=Array("flink","  [field:link /]  ",313,381);
$z[1][4]['row']="10";
$z[1][4]['type']="textall";
$z[2]=Array("flink"," [field:link /] ",637,703);
$z[2][4]['row']="10";
$z[2][4]['type']="textall";
$z[3]=Array("global","",1084,1111);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("global","",1138,1166);
$z[4][4]['name']="cfg_indexname";
$z[5]=Array("global","",1169,1197);
$z[5][4]['name']="cfg_indexname";
$z[6]=Array("channel","|\r\n                     <a href=\"[field:typelink/]\" class=\"nav-alink\" title=\"[field:typename/]\"> [field:typename/]</a>\r\n                     ",1201,1389);
$z[6][4]['type']="top";
$z[7]=Array("global","",1558,1580);
$z[7][4]['name']="cfg_tel";
$z[8]=Array("global","",1656,1682);
$z[8][4]['name']="cfg_powerby";

?>