<?php
$z[0]=Array("channel","\r\n                    <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                    ",232,519);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[0][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[1]=Array("global","",607,633);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",640,661);
$z[2][4]['name']="cfg_dz";
$z[3]=Array("global","",676,698);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",713,734);
$z[4][4]['name']="cfg_cz";
$z[5]=Array("global","",953,979);
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",980,1004);
$z[6][4]['name']="cfg_beian";

?>