<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\"><span>友情链接：</span></a>",204,298);
$z[0][4]['typeid']="1";
$z[1]=Array("flink"," [field:link /] ",299,364);
$z[1][4]['row']="10";
$z[1][4]['type']="textall";
$z[2]=Array("flink"," [field:link /] ",578,643);
$z[2][4]['row']="10";
$z[2][4]['type']="textall";
$z[3]=Array("global","",867,894);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("global","",921,949);
$z[4][4]['name']="cfg_indexname";
$z[5]=Array("global","",952,980);
$z[5][4]['name']="cfg_indexname";
$z[6]=Array("channel","|\r\n                    <a href=\"[field:typelink/]\" class=\"nav-alink\" title=\"[field:typename/]\"> [field:typename/]</a> ",984,1144);
$z[6][4]['type']="top";
$z[7]=Array("global","",1266,1292);
$z[7][4]['name']="cfg_webname";
$z[8]=Array("global","",1299,1320);
$z[8][4]['name']="cfg_dz";
$z[9]=Array("global","",1335,1357);
$z[9][4]['name']="cfg_tel";
$z[10]=Array("global","",1372,1393);
$z[10][4]['name']="cfg_cz";
$z[11]=Array("global","",1455,1476);
$z[11][4]['name']="cfg_qq";
$z[12]=Array("global","",1746,1772);
$z[12][4]['name']="cfg_powerby";
$z[13]=Array("global","",1773,1797);
$z[13][4]['name']="cfg_beian";

?>