<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\"><span>友情链接：</span></a>",195,289);
$z[0][4]['typeid']="9";
$z[1]=Array("flink","  [field:link /]  ",313,381);
$z[1][4]['row']="10";
$z[1][4]['type']="textall";
$z[2]=Array("flink"," [field:link /] ",637,703);
$z[2][4]['row']="10";
$z[2][4]['type']="textall";
$z[3]=Array("global","",1084,1111);
$z[3][4]['name']="cfg_indexurl";
$z[4]=Array("global","",1138,1166);
$z[4][4]['name']="cfg_indexname";
$z[5]=Array("global","",1169,1197);
$z[5][4]['name']="cfg_indexname";
$z[6]=Array("channel","|\r\n                     <a href=\"[field:typelink/]\" class=\"nav-alink\" title=\"[field:typename/]\"> [field:typename/]</a>\r\n                     ",1201,1389);
$z[6][4]['type']="top";
$z[7]=Array("global","",1561,1587);
$z[7][4]['name']="cfg_webname";
$z[8]=Array("global","",1608,1632);
$z[8][4]['name']="cfg_beian";
$z[9]=Array("global","",1638,1659);
$z[9][4]['name']="cfg_dz";
$z[10]=Array("global","",1674,1696);
$z[10][4]['name']="cfg_tel";
$z[11]=Array("global","",1711,1732);
$z[11][4]['name']="cfg_cz";
$z[12]=Array("global","",2061,2087);
$z[12][4]['name']="cfg_powerby";

?>