<?php
$z[0]=Array("global","",1132,1160);
$z[0][4]['name']="cfg_indexname";
$z[1]=Array("global","",1188,1216);
$z[1][4]['name']="cfg_indexname";
$z[2]=Array("channelartlist","\r\n      <li id=\"about\" class=\"nav-lilink {dede:field name='hover'/}\"><a href=\"{dede:field name='typeurl'/}\" class=\"nav-alink\" title=\"{dede:field name='typename'/}\"\r\n                       > {dede:field name='typename'/}</a>\r\n        <div class=\"exnav\">\r\n          <ul class=\"children level-0\">\r\n            {dede:channel   type ='son'    }\r\n            <li class='li-level-1 item-li'>\r\n              <div class=\"cat-item\">\r\n                <div class='cat-name cat-name-1 cat-name-z' id='cat-id-26678'><a href=\"[field:typelink/]\"> [field:typename/]</a></div>\r\n              </div>\r\n            </li>\r\n            {/dede:channel}\r\n          </ul>\r\n        </div>\r\n      </li>\r\n      ",1344,2082);
$z[2][4]['typeid']="top";
$z[3]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n          ",2903,3113);
$z[3][4]['row']="5";
$z[3][4]['typeid']="18";
$z[4]=Array("global","",3441,3466);
$z[4][4]['name']="cfg_cmsurl";

?>