<?php
$z[0]=Array("field","",1195,1254);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\r\n            <li class='li-level-1 item-li'>\r\n              <div class=\"cat-item\">\r\n                <div class='cat-name cat-name-1 cat-name-z' id='cat-id-26678'><a href=\"[field:typelink/]\"> [field:typename/]</a></div>\r\n              </div>\r\n            </li>\r\n            ",1452,2045);
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li class='li-level-1 curr'> <div class='cat-item'> <div class='cat-name cat-name-1 cat-name-z' id='cat-id-26678'><a href='~typelink~'> ~typename~</a></div> </div> </li>";
$z[2]=Array("type","\r\n      <div class=\"hd\"><span class=\"blk_t blk_t01\"><a href=\"[field:typelink/]\">[field:typename/]</a></span> </div>\r\n      ",2302,2459);
$z[2][4]['typeid']="9";
$z[3]=Array("global","",2599,2620);
$z[3][4]['name']="cfg_dz";
$z[4]=Array("global","",2665,2687);
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",2732,2753);
$z[5][4]['name']="cfg_cz";
$z[6]=Array("global","",2794,2815);
$z[6][4]['name']="cfg_qq";
$z[7]=Array("global","",2860,2881);
$z[7][4]['name']="cfg_wz";

?>