<?php
$z[0]=Array("field","",1228,1287);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\n                        <li class='li-level-1 item-li'>\n                            <div class=\"cat-item\">\n                                <div class='cat-name cat-name-1 cat-name-z' id='cat-id-26678'><a href=\"[field:typelink/]\"> [field:typename/]</a></div>\n                            </div>\n                        </li>\n                        ",1523,2260);
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li class='li-level-1 curr'> <div class='cat-item'> <div class='cat-name cat-name-1 cat-name-z' id='cat-id-26678'><a href='~typelink~'> ~typename~</a></div> </div> </li>";
$z[2]=Array("type","\n            <div class=\"hd\"><span class=\"blk_t blk_t01\"><a href=\"[field:typelink/]\">[field:typename/]</a></span> </div>\n            ",2555,2722);
$z[2][4]['typeid']="4";
$z[3]=Array("global","",2928,2949);
$z[3][4]['name']="cfg_dz";
$z[4]=Array("global","",3003,3025);
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",3079,3100);
$z[5][4]['name']="cfg_cz";
$z[6]=Array("global","",3150,3171);
$z[6][4]['name']="cfg_qq";
$z[7]=Array("global","",3225,3246);
$z[7][4]['name']="cfg_wz";

?>