<?php
$z[0]=Array("field","",1262,1321);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\r\n                        <li class='li-level-1 item-li'>\r\n                            <div class=\"cat-item\">\r\n                                <div class='cat-name cat-name-1 cat-name-z' id='cat-id-26678'><a href=\"[field:typelink/]\"> [field:typename/]</a></div>\r\n                            </div>\r\n                        </li>\r\n                        ",1563,2312);
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li class='li-level-1 curr'> <div class='cat-item'> <div class='cat-name cat-name-1 cat-name-z' id='cat-id-26678'><a href='~typelink~'> ~typename~</a></div> </div> </li>";
$z[2]=Array("type","\r\n            <div class=\"hd\"><span class=\"blk_t blk_t01\"><a href=\"[field:typelink/]\">[field:typename/]</a></span> </div>\r\n            ",2617,2786);
$z[2][4]['typeid']="9";
$z[3]=Array("global","",2998,3019);
$z[3][4]['name']="cfg_dz";
$z[4]=Array("global","",3074,3096);
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",3151,3172);
$z[5][4]['name']="cfg_cz";
$z[6]=Array("global","",3223,3244);
$z[6][4]['name']="cfg_qq";
$z[7]=Array("global","",3299,3320);
$z[7][4]['name']="cfg_wz";

?>