<?php
$z[0]=Array("field","",1195,1254);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\r\n            <li class='li-level-1 item-li'>\r\n              <div class=\"cat-item\">\r\n                <div class='cat-name cat-name-1 cat-name-z' id='cat-id-26678'><a href=\"[field:typelink/]\"> [field:typename/]</a></div>\r\n              </div>\r\n            </li>\r\n            ",1452,2045);
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="<li class='li-level-1 curr'> <div class='cat-item'> <div class='cat-name cat-name-1 cat-name-z' id='cat-id-26678'><a href='~typelink~'> ~typename~</a></div> </div> </li>";
$z[2]=Array("type","\r\n      <div class=\"hd\"><span class=\"blk_t blk_t01\"><a href=\"[field:typelink/]\">[field:typename/]</a></span> </div>\r\n      ",2302,2459);
$z[2][4]['typeid']="9";
$z[3]=Array("global","",2605,2627);
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",2678,2704);
$z[4][4]['name']="cfg_hotline";
$z[5]=Array("global","",2755,2780);
$z[5][4]['name']="cfg_mobile";
$z[6]=Array("global","",2825,2849);
$z[6][4]['name']="cfg_email";
$z[7]=Array("global","",2894,2920);
$z[7][4]['name']="cfg_address";
$z[8]=Array("global","",3017,3038);
$z[8][4]['name']="cfg_qq";
$z[9]=Array("global","",3103,3124);
$z[9][4]['name']="cfg_qq";

?>