<?php
$z[0]=Array("field","",209,228);
$z[0][4]['name']="title";
$z[1]=Array("global","",229,255);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",297,326);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",367,426);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3083,3118);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",3255,3290);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",3372,3433);
$z[6][4]['name']="typename";
$z[6][4]['function']="”GetTypeName(@me)”";
$z[7]=Array("field","",3507,3536);
$z[7][4]['name']="position";
$z[8]=Array("list","\n                 		<li class=\"newprod_list\">\n                 			<div class=\"newprod_pic\"><a href=\"[field:arcurl/]\" target=\"_blank\" class=\"pro_img_link\"><img dataid=\"289098\" width=\"220\" src=\"[field:picname/]\" alt=\"[field:title/]\" class=\"289098\" height=\"165\" /></a>\n                 		  </div>\n                 			<div class=\"newprod_name\"><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]}\">[field:title/]</a></div>\n                 		</li>\n                 		 ",3781,4294);
$z[8][4]['pagesize']="9";
$z[9]=Array("include","",4559,4596);
$z[9][4]['filename']="footer.htm";

?>