<?php
$z[0]=Array("field","",215,234);
$z[0][4]['name']="title";
$z[1]=Array("field","",276,305);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",346,405);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",3232,3267);
$z[3][4]['filename']="head.htm";
$z[4]=Array("include","",3348,3383);
$z[4][4]['filename']="left.htm";
$z[5]=Array("field","",3594,3655);
$z[5][4]['name']="typename";
$z[5][4]['function']="”GetTypeName(@me)”";
$z[6]=Array("list","\r\n							<li class=\"newprod_list\">\r\n								<div class=\"newprod_pic\"><a href=\"[field:arcurl/]\" class=\"pro_img_link\"><img dataid=\"289098\" width=\"220\" src=\"[field:picname/]\" alt=\"[field:title/]\" class=\"289098\" height=\"165\" /></a>\r\n								</div>\r\n								<div class=\"newprod_name\"><a href=\"[field:arcurl/]\" title=\"[field:title/]}\">[field:title/]</a></div>\r\n							</li>\r\n							",3819,4240);
$z[6][4]['pagesize']="9";
$z[6][4]['row']="3";
$z[7]=Array("pagelist","",4336,4377);
$z[7][4]['listsize']="5";
$z[7][4]['listitem']="";
$z[8]=Array("include","",4499,4536);
$z[8][4]['filename']="footer.htm";

?>