<?php
$z[0]=Array("field","",214,233);
$z[0][4]['name']="title";
$z[1]=Array("global","",234,260);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",303,332);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",374,433);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3149,3184);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",3325,3360);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",3611,3672);
$z[6][4]['name']="typename";
$z[6][4]['function']="”GetTypeName(@me)”";
$z[7]=Array("list","\r\n                 		<li class=\"newprod_list\">\r\n                 			<div class=\"newprod_pic\"><a href=\"[field:arcurl/]\"  class=\"pro_img_link\"><img dataid=\"289098\" width=\"220\" src=\"[field:picname/]\" alt=\"[field:title/]\" class=\"289098\" height=\"165\" /></a>\r\n                 		  </div>\r\n                 			<div class=\"newprod_name\"><a href=\"[field:arcurl/]\"  title=\"[field:title/]}\">[field:title/]</a></div>\r\n                 		</li>\r\n                 		 ",3952,4441);
$z[7][4]['pagesize']="9";
$z[8]=Array("include","",4715,4752);
$z[8][4]['filename']="footer.htm";

?>