<?php
$z[0]=Array("field","",250,269);
$z[0][4]['name']="title";
$z[1]=Array("global","",270,296);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",336,365);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",404,462);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",878,913);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1073,1102);
$z[5][4]['name']="position";
$z[6]=Array("field","",1200,1258);
$z[6][4]['name']="typeid";
$z[6][4]['function']="GetTopTypename(@me)";
$z[7]=Array("channel","\n        <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\n        ",1284,1515);
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="<li><a href='~typelink~' class='con'>~typename~</a></li>";
$z[8]=Array("global","",1630,1651);
$z[8][4]['name']="cfg_dz";
$z[9]=Array("global","",1675,1697);
$z[9][4]['name']="cfg_tel";
$z[10]=Array("global","",1721,1742);
$z[10][4]['name']="cfg_cz";
$z[11]=Array("global","",1764,1785);
$z[11][4]['name']="cfg_qq";
$z[12]=Array("list","\n            <li><i><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\"><img src=\"[field:picname/]\" border=\"0\" onload=\"DrawImage(this,200,140);\" /></a></i>\n              <h1><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title/]</a></h1>\n            </li>\n            ",2039,2382);
$z[12][4]['pagesize']="18";
$z[13]=Array("include","",2623,2660);
$z[13][4]['filename']="footer.htm";

?>