<?php
$z[0]=Array("field","",210,229);
$z[0][4]['name']="title";
$z[1]=Array("field","",271,300);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",341,400);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",3164,3199);
$z[3][4]['filename']="head.htm";
$z[4]=Array("include","",3280,3315);
$z[4][4]['filename']="left.htm";
$z[5]=Array("field","",3526,3587);
$z[5][4]['name']="typename";
$z[5][4]['function']="”GetTypeName(@me)”";
$z[6]=Array("list","\r\n								<tr>\r\n									<td width=\"82%\" height=\"40\" align=\"left\" valign=\"middle\" class=\"heis\" style=\" border-bottom:#cccccc dashed 1px\"><a href=\"[field:arcurl/]\"><span style=\"color:#055a97; font-weight:bold\">[公司新闻]</span></a>&nbsp;&nbsp;<a href=\"[field:arcurl/]\" class=\"heis\" >&nbsp; &gt;&gt; [field:title/]</a></td>\r\n									<td width=\"18%\" align=\"right\" valign=\"middle\" class=\"heis\" style=\" border-bottom:#cccccc dashed 1px\">[[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]]&nbsp; </td>\r\n								</tr>\r\n								",3828,4388);
$z[6][4]['pagesize']="9";
$z[7]=Array("pagelist","",4493,4534);
$z[7][4]['listsize']="5";
$z[7][4]['listitem']="";
$z[8]=Array("include","",4656,4693);
$z[8][4]['filename']="footer.htm";

?>