<?php
$z[0]=Array("field","",210,229);
$z[0][4]['name']="title";
$z[1]=Array("global","",230,256);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",298,327);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",368,427);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3191,3226);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",3307,3342);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",3553,3614);
$z[6][4]['name']="typename";
$z[6][4]['function']="”GetTypeName(@me)”";
$z[7]=Array("list","\r\n								<tr>\r\n									<td width=\"82%\" height=\"40\" align=\"left\" valign=\"middle\" class=\"heis\" style=\" border-bottom:#cccccc dashed 1px\"><a href=\"[field:arcurl/]\"><span style=\"color:#055a97; font-weight:bold\">[公司新闻]</span></a>&nbsp;&nbsp;<a href=\"[field:arcurl/]\" class=\"heis\" >&nbsp; &gt;&gt; [field:title/]</a></td>\r\n									<td width=\"18%\" align=\"right\" valign=\"middle\" class=\"heis\" style=\" border-bottom:#cccccc dashed 1px\">[[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]]&nbsp; </td>\r\n								</tr>\r\n								",3855,4415);
$z[7][4]['pagesize']="9";
$z[8]=Array("include","",4560,4597);
$z[8][4]['filename']="footer.htm";

?>