<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",830,865);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1031,1060);
$z[5][4]['name']="position";
$z[6]=Array("field","",1162,1220);
$z[6][4]['name']="typeid";
$z[6][4]['function']="GetTopTypename(@me)";
$z[7]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n        ",1248,1483);
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="<li><a href='~typelink~' class='con'>~typename~</a></li>";
$z[8]=Array("global","",1602,1623);
$z[8][4]['name']="cfg_dz";
$z[9]=Array("global","",1648,1670);
$z[9][4]['name']="cfg_tel";
$z[10]=Array("global","",1695,1716);
$z[10][4]['name']="cfg_cz";
$z[11]=Array("list","\r\n            <li>\r\n              <h1><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_blank\">[field:title/]</a></h1>\r\n              <i>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</i></li>\r\n            ",2015,2267);
$z[11][4]['pagesize']="18";
$z[12]=Array("include","",2519,2556);
$z[12][4]['filename']="footer.htm";

?>